### ISSUE TITLE
Serializing without encapsulation

### ISSUE THREAD

**Issue by birkenfeld** [hrektts/cdr-rs#1]
I'd like to implement a GIOP/IIOP interface using this crate. However, there is no 4-byte encapsulation header in this protocol; the byte order is marked in the encoded stream (in non-byte-order-sensitive types).

Would it be possible to introduce API to encode without the header, and to specify the encapsulation in the decode call? Otherwise I can't use the `_into`/`_from` APIs and have to use allocations.

**Comment by hrektts** [comment]
Thanks for looking at cdr! I think it can be done as follows:

```rust
extern crate byteorder;
extern crate cdr;
#[macro_use]
extern crate serde_derive;

use byteorder::BigEndian;
use cdr::Infinite;

#[derive(Deserialize, Serialize, PartialEq)]
struct Point {
    x: f64,
    y: f64,
}

#[derive(Deserialize, Serialize, PartialEq)]
struct Polygon(Vec<Point>);

fn main() {
    let triangle = Polygon(vec![
        Point { x: -1.0, y: -1.0 },
        Point { x: 1.0, y: -1.0 },
        Point { x: 0.0, y: 0.73 },
    ]);

    let size = cdr::calc_serialized_size(&triangle);
    let size_without_encapsulation = cdr::size::calc_serialized_data_size(&triangle);

    assert_eq!(size - size_without_encapsulation, 4);

    let encoded = cdr::ser::serialize_data::<_, _, BigEndian>(&triangle, Infinite).unwrap();
    let decoded = cdr::de::deserialize_data::<Polygon, BigEndian>(&encoded[..]).unwrap();

    assert!(triangle == decoded);
}
```

**Comment by birkenfeld** [comment]
Ah, you can directly use APIs in `cdr::ser` and `cdr::de`! Sorry, I should have looked closer. That's exactly what I need.
