### ISSUE TITLE
Reading uninitialized memory can cause UB (`Deserializer::read_vec`)

### ISSUE THREAD

**Issue by JOE1994** [hrektts/cdr-rs#10]
Hello :crab: ,
we (Rust group @sslab-gatech) found a memory-safety/soundness issue in this crate while scanning Rust code on crates.io for potential vulnerabilities.

## Issue Description
https://github.com/hrektts/cdr-rs/blob/880a281afe6f49109a90e2a8bb943c02a360bf49/src/de.rs#L70-L77

`Deserializer::read_vec` method creates an uninitialized buffer and passes it to user-provided Read implementation (`self.reader.read_exact`). This is unsound, because it allows safe Rust code to exhibit an undefined behavior (read from uninitialized memory).

### Suggested Fix

It is safe to zero-initialize the newly allocated part of `u8` buffer before read(), in order to prevent user-provided Read from getting access to the old contents from the newly allocated heap memory.

Thank you for checking out this issue :+1:

**Comment by JOE1994** [comment]
@hrektts  Thank you for the fix! Would you also mind publishing a new release containing the fix to crates.io ?

**Comment by hrektts** [comment]
@JOE1994 It is published. Thank you for your follow-up.
