### ISSUE TITLE
Address Clippy Warnings

### ISSUE THREAD

**Issue by kydos** [hrektts/cdr-rs#13]
Hello,

First of thanks for contributing the CDR codec, this has helped us a lot in getting zenoh (see https://github.com/eclipse-zenoh/zenoh and http://zenoh.io) seamlessly read/write data from DDS and ROS2.

As a little contribution on our side, we'd like to eliminate all clippy warning, as you'll see by running ```cargo clippy``` there is at least one that is quite important on the ```de.rs | read_vec```. 

I'll do a pull request right off with the fixes. Ideally would be good to have ```cargo clippy``` run as part of the GitHub actions.

Thanks!

- kydos

**Comment by hrektts** [comment]
Thank you for the fix and for letting me know about your project.
Interoperability between DDS-based systems such as ROS2 and other systems may lead to new applications. It seems interesting!
